# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolov5-infer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolov5-infer
  template:
    metadata:
      labels:
        app: yolov5-infer
    spec:
      nodeSelector:
        type: atlas200
      containers:
      - name: yolov5-infer
        image: 192.168.137.2:5000/yolov5-infer:latest
        ports:
        - containerPort: 80
        env:
        - name: ASCEND_VISIBLE_DEVICES
          value: "0"
        - name: ASCEND_ALLOW_LINK
          value: "True"
        volumeMounts:
        - mountPath: /dev/svm0
          name: dev-svm0
        - mountPath: /dev/ts_aisle
          name: dev-ts-aisle
        - mountPath: /dev/upgrade
          name: dev-upgrade
        - mountPath: /dev/sys
          name: dev-sys
        - mountPath: /dev/vdec
          name: dev-vdec
        - mountPath: /dev/vpc
          name: dev-vpc
        - mountPath: /dev/pngd
          name: dev-pngd
        - mountPath: /dev/venc
          name: dev-venc
        - mountPath: /dev/dvpp_cmdlist
          name: dev-dvpp-cmdlist
        - mountPath: /dev/log_drv
          name: dev-log-drv
        - mountPath: /etc/sys_version.conf
          name: sys-version-conf
        - mountPath: /etc/hdcBasic.cfg
          name: hdc-basic-cfg
        - mountPath: /usr/local/sbin/npu-smi
          name: npu-smi
        - mountPath: /usr/local/Ascend/driver/lib64
          name: ascend-driver-lib64
        - mountPath: /usr/lib64/aicpu_kernels/
          name: aicpu-kernels
        - mountPath: /var/slogd
          name: slogd
        - mountPath: /var/dmp_daemon
          name: dmp-daemon
        - mountPath: /usr/lib64/libaicpu_processer.so
          name: libaicpu-processer
        - mountPath: /usr/lib64/libaicpu_prof.so
          name: libaicpu-prof
        - mountPath: /usr/lib64/libaicpu_sharder.so
          name: libaicpu-sharder
        - mountPath: /usr/lib64/libadump.so
          name: libadump
        - mountPath: /usr/lib64/libtsd_eventclient.so
          name: libtsd-eventclient
        - mountPath: /usr/lib64/libaicpu_scheduler.so
          name: libaicpu-scheduler
        - mountPath: /usr/lib64/libdcmi.so
          name: libdcmi
        - mountPath: /usr/lib64/libmpi_dvpp_adapter.so
          name: libmpi-dvpp-adapter
        - mountPath: /usr/lib64/libstackcore.so
          name: libstackcore
        - mountPath: /usr/local/Ascend/driver
          name: ascend-driver
        - mountPath: /etc/ascend_install.info
          name: ascend-install-info
        - mountPath: /var/log/ascend_seclog
          name: ascend-seclog
        - mountPath: /var/davinci/driver
          name: davinci-driver
        - mountPath: /usr/lib64/libc_sec.so
          name: libc-sec
        - mountPath: /usr/lib64/libdevmmap.so
          name: libdevmmap
        - mountPath: /usr/lib64/libdrvdsmi.so
          name: libdrvdsmi
        - mountPath: /usr/lib64/libslog.so
          name: libslog
        - mountPath: /usr/lib64/libmmpa.so
          name: libmmpa
        - mountPath: /usr/lib64/libascend_hal.so
          name: libascend-hal
        - mountPath: /usr/local/Ascend/ascend-toolkit
          name: ascend-toolkit
        securityContext:
          privileged: true

      volumes:
      - name: dev-svm0
        hostPath:
          path: /dev/svm0
      - name: dev-ts-aisle
        hostPath:
          path: /dev/ts_aisle
      - name: dev-upgrade
        hostPath:
          path: /dev/upgrade
      - name: dev-sys
        hostPath:
          path: /dev/sys
      - name: dev-vdec
        hostPath:
          path: /dev/vdec
      - name: dev-vpc
        hostPath:
          path: /dev/vpc
      - name: dev-pngd
        hostPath:
          path: /dev/pngd
      - name: dev-venc
        hostPath:
          path: /dev/venc
      - name: dev-dvpp-cmdlist
        hostPath:
          path: /dev/dvpp_cmdlist
      - name: dev-log-drv
        hostPath:
          path: /dev/log_drv
      - name: sys-version-conf
        hostPath:
          path: /etc/sys_version.conf
      - name: hdc-basic-cfg
        hostPath:
          path: /etc/hdcBasic.cfg
      - name: npu-smi
        hostPath:
          path: /usr/local/sbin/npu-smi
      - name: ascend-driver-lib64
        hostPath:
          path: /usr/local/Ascend/driver/lib64
      - name: aicpu-kernels
        hostPath:
          path: /usr/lib64/aicpu_kernels/
      - name: slogd
        hostPath:
          path: /var/slogd
      - name: dmp-daemon
        hostPath:
          path: /var/dmp_daemon
      - name: libaicpu-processer
        hostPath:
          path: /usr/lib64/libaicpu_processer.so
      - name: libaicpu-prof
        hostPath:
          path: /usr/lib64/libaicpu_prof.so
      - name: libaicpu-sharder
        hostPath:
          path: /usr/lib64/libaicpu_sharder.so
      - name: libadump
        hostPath:
          path: /usr/lib64/libadump.so
      - name: libtsd-eventclient
        hostPath:
          path: /usr/lib64/libtsd_eventclient.so
      - name: libaicpu-scheduler
        hostPath:
          path: /usr/lib64/libaicpu_scheduler.so
      - name: libdcmi
        hostPath:
          path: /usr/lib64/libdcmi.so
      - name: libmpi-dvpp-adapter
        hostPath:
          path: /usr/lib64/libmpi_dvpp_adapter.so
      - name: libstackcore
        hostPath:
          path: /usr/lib64/libstackcore.so
      - name: ascend-driver
        hostPath:
          path: /usr/local/Ascend/driver
      - name: ascend-install-info
        hostPath:
          path: /etc/ascend_install.info
      - name: ascend-seclog
        hostPath:
          path: /var/log/ascend_seclog
      - name: davinci-driver
        hostPath:
          path: /var/davinci/driver
      - name: libc-sec
        hostPath:
          path: /usr/lib64/libc_sec.so
      - name: libdevmmap
        hostPath:
          path: /usr/lib64/libdevmmap.so
      - name: libdrvdsmi
        hostPath:
          path: /usr/lib64/libdrvdsmi.so
      - name: libslog
        hostPath:
          path: /usr/lib64/libslog.so
      - name: libmmpa
        hostPath:
          path: /usr/lib64/libmmpa.so
      - name: libascend-hal
        hostPath:
          path: /usr/lib64/libascend_hal.so
      - name: ascend-toolkit
        hostPath:
          path: /usr/local/Ascend/ascend-toolkit

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: yolov5-infer-service
spec:
  selector:
    app: yolov5-infer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80

---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yolov5-infer-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: yolov5-infer-service
            port:
              number: 8080
